
import { RegionId } from '../types';

export const TL = {
  regions: {
    [RegionId.RUST_VALLEY]: { RU: "Ржавая Долина", EN: "Rust Valley" },
    [RegionId.CRYSTAL_WASTES]: { RU: "Кристальные Пустоши", EN: "Crystal Wastes" },
    [RegionId.IRON_GATES]: { RU: "Железные Врата", EN: "Iron Gates" },
    [RegionId.MAGMA_CORE]: { RU: "Магматическое Ядро", EN: "Magma Core" },
    [RegionId.VOID_CHASM]: { RU: "Разлом Пустоты", EN: "Void Chasm" }
  },
  regionDescriptions: {
    [RegionId.RUST_VALLEY]: { RU: "Стартовый регион. Зона нелегальных бурильщиков, бандиты и коррозия.", EN: "Starting region. Zone of illegal drillers, bandits, and corrosion." },
    [RegionId.CRYSTAL_WASTES]: { RU: "Заброшенные кристаллические шахты Science Faction. Изумруды ×3, магнитные аномалии.", EN: "Abandoned crystal mines of the Science Faction. Emeralds ×3, magnetic anomalies." },
    [RegionId.IRON_GATES]: { RU: "Военная зона Void Industries. Железо ×2, контроль корпораций, патрули дронов.", EN: "Military zone of Void Industries. Iron ×2, corporate control, drone patrols." },
    [RegionId.MAGMA_CORE]: { RU: "Вулканический регион. Экстремальные температуры, древние руины, лавовые потоки.", EN: "Volcanic region. Extreme temperatures, ancient ruins, lava flows." },
    [RegionId.VOID_CHASM]: { RU: "Аномальная зона. Пространственные разрывы, Ancient Tech ×3, подготовка к порталу.", EN: "Anomalous zone. Spatial ruptures, Ancient Tech ×3, portal preparation." }
  },
  baseTypes: {
    outpost: { RU: "Аванпост", EN: "Outpost" },
    station: { RU: "Станция", EN: "Station" },
    camp: { RU: "Лагерь", EN: "Camp" },
    citadel: { RU: "Цитадель", EN: "Citadel" }
  },
  ui: {
    map: { RU: "Карта", EN: "Map" },
    market: { RU: "Рынок", EN: "Market" },
    caravans: { RU: "Караваны", EN: "Caravans" },
    quests: { RU: "Квесты", EN: "Quests" },
    factions: { RU: "Фракции", EN: "Factions" },
    quantity: { RU: "Количество", EN: "Quantity" },
    sector: { RU: "СЕКТОР", EN: "SECTOR" },
    status: { RU: "СТАТУС", EN: "STATUS" },
    active: { RU: "АКТИВЕН", EN: "ACTIVE" },
    currentRegion: { RU: "Текущий регион", EN: "Current Region" },
    cargo: { RU: "Груз", EN: "Cargo" },
    fuel: { RU: "Топливо", EN: "Fuel" },
    level: { RU: "Уровень", EN: "Level" },
    travelTo: { RU: "Перемещение в", EN: "Travel To" },
    distance: { RU: "Расстояние", EN: "Distance" },
    startTravel: { RU: "НАЧАТЬ ПЕРЕМЕЩЕНИЕ", EN: "START TRAVEL" },
    overloaded: { RU: "ПЕРЕГРУЗ! СБРОСЬТЕ ГРУЗ", EN: "OVERLOADED! DUMP CARGO" },
    selectFuel: { RU: "Выбор топлива:", EN: "Select Fuel:" },
    cargoState: { RU: "Состояние груза:", EN: "Cargo State:" },
    loaded: { RU: "загружен", EN: "loaded" },
    consumption: { RU: "расход", EN: "consumption" },
    locked: { RU: "🔒", EN: "🔒" },
    available: { RU: "Доступно", EN: "Available" },
    cost: { RU: "Стоимость", EN: "Cost" },
    sell: { RU: "Продать", EN: "Sell" },
    buy: { RU: "Купить", EN: "Buy" },
    price: { RU: "Цена", EN: "Price" },
    status_label: { RU: "СТАТУС", EN: "STATUS" },
    level_label: { RU: "УРОВЕНЬ", EN: "LEVEL" },
    features: { RU: "Особенности", EN: "Features" },
    build_time: { RU: "Время постройки", EN: "Build Time" },
    storage_capacity: { RU: "Объем хранилища", EN: "Storage Capacity" },
    requirements: { RU: "Требования", EN: "Requirements" },
    upgrade_base: { RU: "МОДЕРНИЗАЦИЯ БАЗЫ", EN: "BASE UPGRADE" },
    start_upgrade: { RU: "НАЧАТЬ УЛУЧШЕНИЕ", EN: "START UPGRADE" },
    storage_fill: { RU: "Заполнение хранилища", EN: "Storage Fill" },
    in_base: { RU: "На базе", EN: "In Base" },
    to_storage_100: { RU: "В ХРАН. (100)", EN: "TO STORAGE (100)" },
    build_facility: { RU: "ПОСТРОИТЬ МОДУЛЬ", EN: "BUILD FACILITY" },
    facility_operational: { RU: "МОДУЛЬ ФУНКЦИОНИРУЕТ", EN: "FACILITY OPERATIONAL" },
    base_integrity: { RU: "Целостность базы", EN: "Base Integrity" },
    repair_base_btn: { RU: "Отремонтировать", EN: "Repair Base" },
    shield_power: { RU: "Мощность щита", EN: "Shield Power" },
    defense_rating: { RU: "Сила Обороны", EN: "Defense Rating" },
    dp_per_unit: { RU: "DP за единицу", EN: "DP per unit" },
    in_production: { RU: "В производстве:", EN: "In production:" },
    start_production: { RU: "ЗАПУСТИТЬ ПРОИЗВОДСТВО", EN: "START PRODUCTION" },
    sector_access: { RU: "ДОСТУП К СЕКТОРУ", EN: "SECTOR ACCESS" },
    base_id: { RU: "ID БАЗЫ", EN: "BASE ID" },
    market_unavailable: { RU: "РЫНОК НЕДОСТУПЕН", EN: "MARKET UNAVAILABLE" },
    market_station_required: { RU: "Рынок доступен только на Станциях. Постройте Станцию в этом регионе.", EN: "Market only available at Stations. Build a Station in this region." },
    shadow_network: { RU: "ТЕНЕВАЯ СЕТЬ", EN: "SHADOW NETWORK" },
    acquire: { RU: "ПРИОБРЕСТИ", EN: "ACQUIRE" },
    shadow_warning: { RU: "ВНИМАНИЕ: ТРАНЗАКЦИИ НЕОТСЛЕЖИВАЕМЫ. ВОЗВРАТ НЕВОЗМОЖЕН.", EN: "WARNING: TRANSACTIONS ARE UNTRACEABLE. NO REFUNDS." },
    max_coal: { RU: "Максимум угля", EN: "Max Coal" },
    exchange_all: { RU: "ОБМЕНЯТЬ ВСЁ", EN: "EXCHANGE ALL" },
    minimum_10: { RU: "МИНИМУМ 10", EN: "MINIMUM 10" },
    no_exchange_res: { RU: "Нет доступных ресурсов для обмена", EN: "No resources available for exchange" },
    select_res_list: { RU: "Выберите ресурс из списка", EN: "Select resource from the list" },
    build_base_title: { RU: "ПОСТРОЙКА БАЗЫ", EN: "BUILD BASE" },
    region_label: { RU: "Регион", EN: "Region" },
    tip_label: { RU: "Подсказка", EN: "Tip" },
    one_base_per_region: { RU: "В каждом регионе может быть только ОДНА база. Выбирайте с умом!", EN: "Each region can only have ONE base. Choose wisely!" },
    storage: { RU: "Хранилище", EN: "Storage" },
    facilities: { RU: "Модули", EN: "Facilities" },
    refinery: { RU: "Переработка", EN: "Refinery" },
    workshop: { RU: "Мастерская", EN: "Workshop" },
    garrison: { RU: "Гарнизон", EN: "Garrison" },
    baseModules: { RU: "Базовые Модули", EN: "Base Modules" },
    activateModule: { RU: "АКТИВИРОВАТЬ МОДУЛЬ", EN: "ACTIVATE MODULE" },
    upgradeModule_btn: { RU: "УЛУЧШИТЬ МОДУЛЬ", EN: "UPGRADE MODULE" },
    maxLevel: { RU: "МАКС. УРОВЕНЬ", EN: "MAX LEVEL" },

    // Новые ключи для полной локализации
    creditReserve: { RU: "РЕЗЕРВ КРЕДИТОВ", EN: "CREDIT RESERVE" },
    rawMaterialType: { RU: "Тип: СЫРЬЕ", EN: "Type: RAW MATERIAL" },
    inCargo: { RU: "В грузовом отсеке", EN: "In Cargo" },
    terminalStatus: { RU: "Статус терминала", EN: "Terminal Status" },
    processConversion: { RU: "ПРОЦЕСС КОНВЕРСИИ", EN: "CONVERSION PROCESS" },
    activeAssemblies: { RU: "Активные сборки", EN: "Active Assemblies" },
    powerGrid: { RU: "Энергосеть", EN: "Power Grid" },
    energyShortage: { RU: "Дефицит энергии!", EN: "Energy Shortage!" },
    neuroCoreInterface: { RU: "Интерфейс Нейро-Ядра", EN: "Neuro-Core Interface" },
    nextBonus: { RU: "След. бонус", EN: "Next Bonus" },
    upgradeLink: { RU: "Связь для апгрейда", EN: "Upgrade Link" },
    optimizationComplete: { RU: "Оптимизация завершена", EN: "Optimization Complete" },
    protocolMax: { RU: "Достигнут максимум протокола", EN: "Protocol Max Achieved" },
    fusionRequired: { RU: "Требуется слияние", EN: "Fusion Required" },
    schematicRequired: { RU: "Требуется схема", EN: "Schematic Required" },
    processing: { RU: "ОБРАБОТКА...", EN: "PROCESSING..." },
    initiateUpgrade: { RU: "НАЧАТЬ МОДЕРНИЗАЦИЮ", EN: "INITIATE UPGRADE" },
    insufficientFunds: { RU: "НЕДОСТАТОЧНО СРЕДСТВ", EN: "INSUFFICIENT FUNDS" },
    assemblyState: { RU: "Состояние сборки", EN: "Assembly State" },
    collectItem: { RU: "ЗАБРАТЬ ГОТОВЫЙ ПРЕДМЕТ", EN: "COLLECT READY ITEM" },
    abortOperation: { RU: "ПРЕРВАТЬ ОПЕРАЦИЮ", EN: "ABORT OPERATION" },
    syncProtocol: { RU: "Протокол синхронизации синапсов", EN: "Synapse Synchronization Protocol" },
    neuralBuffer: { RU: "Доступный нейробуфер (Опыт)", EN: "Available Neural Buffer (XP)" },
    syncStatus: { RU: "Статус синхронизации", EN: "Sync Status" },
    moduleCode: { RU: "Код модуля", EN: "Module Code" },
    units: { RU: "ЕД.", EN: "UNITS" },
    reqDepth: { RU: "ТРЕБ. ГЛУБИНА", EN: "REQ. DEPTH" },
    meter_label: { RU: "М", EN: "M" },
    tier: { RU: "ТИР", EN: "TIER" },
    module_label: { RU: "МОДУЛЬ", EN: "MODULE" },
    requiredMaterials: { RU: "НЕОБХОДИМЫЕ МАТЕРИАЛЫ", EN: "REQUIRED MATERIALS" },
    cost_label: { RU: "СТОИМОСТЬ", EN: "COST" },
    max: { RU: "МАКС", EN: "MAX" },
    efficiency: { RU: "ЭФФЕКТИВНОСТЬ", EN: "EFFICIENCY" },
    craft_item: { RU: "СОЗДАТЬ ПРЕДМЕТ", EN: "CRAFT ITEM" },
    godly: { RU: "БОЖЕСТВЕННО", EN: "GODLY" },
    hullStatus: { RU: "Прочность корпуса", EN: "Hull Integrity" },
    heatStatus: { RU: "Температура", EN: "Temperature" },
    pwrLoad: { RU: "Нагрузка", EN: "Power Load" },
    cargoStatus: { RU: "Заполненность", EN: "Cargo Payload" },
    fuelReserve: { RU: "Запас топлива", EN: "Fuel Reserve" },
    heatAlert: { RU: "Аварийная блокировка при 95%", EN: "Emergency lockout at 95%" },
    inventoryTitle: { RU: "ИНВЕНТАРЬ И АРХИВ", EN: "INVENTORY & ARCHIVE" },
    quickAccess: { RU: "БЫСТРЫЙ ДОСТУП", EN: "QUICK ACCESS" },
    empty_label: { RU: "Пусто", EN: "Empty" },
    equipmentTab: { RU: "🔧 ОБОРУДОВАНИЕ", EN: "🔧 EQUIPMENT" },
    artifactsTab: { RU: "💎 АРТЕФАКТЫ", EN: "💎 ARTIFACTS" },
    equipmentStorage: { RU: "Склад Оборудования", EN: "Equipment Storage" },
    resetFilter: { RU: "Сбросить фильтр", EN: "Reset Filter" },
    noItemsFound: { RU: "Ничего не найдено", EN: "Nothing Found" },
    analyzing: { RU: "Выполняется анализ...", EN: "Analyzing..." },
    analysisRequired: { RU: "Требуется анализ", EN: "Analysis Required" },
    sectorId: { RU: "ID СЕКТОРА", EN: "SECTOR ID" },
    scanningActive: { RU: "СТАТУС: СКАН-АКТИВЕН", EN: "STATUS: SCANNING_ACTIVE" },
    authClearance: { RU: "Допуск Авторизации", EN: "Auth Clearance" },
    currentSector: { RU: "Текущий сектор", EN: "Current Sector" },
    cargoLoad: { RU: "Загрузка груза", EN: "Cargo Load" },
    carbonUnits: { RU: "Углеродные единицы", EN: "Carbon Units" },
    expDegree: { RU: "Степень Опыта", EN: "Exp Degree" },
    regionDescriptor: { RU: "Дескриптор региона", EN: "Region Descriptor" },
    propulsionSource: { RU: "Источник тяги", EN: "Propulsion Source" },
    initiateTransit: { RU: "НАЧАТЬ ПРЕЛЕТ", EN: "INITIATE TRANSIT" },
    accessMainframe: { RU: "ВХОД В МЕЙНФРЕЙМ", EN: "ACCESS MAINFRAME" },
    youAreHere: { RU: "ВЫ ЗДЕСЬ", EN: "YOU ARE HERE" },
    awaitingCommand: { RU: "Ожидание команды отклонения", EN: "Awaiting Deviation Command" },
    establishOutpost: { RU: "ОСНОВАТЬ АВАНПОСТ", EN: "ESTABLISH OUTPOST" },
    globalCoordLink: { RU: "Глобальная связь координат", EN: "Global Coord Link" },
    syncOk: { RU: "СИНХРОНИЗАЦИЯ ОК", EN: "SYNC OK" },
    deploymentOrigin: { RU: "Точка развертывания", EN: "Deployment Origin" },
    targetDestination: { RU: "Целевой пункт назначения", EN: "Target Destination" },
    cargoPayload: { RU: "Полезная нагрузка", EN: "Cargo Payload" },
    payloadCap: { RU: "Предел нагрузки", EN: "Payload Cap" },
    routeSyncing: { RU: "Синхронизация маршрута...", EN: "Route Syncing..." },
    initiateSupplyBridge: { RU: "УСТАНОВИТЬ ЛОГИСТИЧЕСКИЙ МОСТ", EN: "INITIATE SUPPLY BRIDGE" },
    subNetFeed: { RU: "Целевой поток подсети", EN: "Sub-Net Target Feed" },
    contractFulfilled: { RU: "Контракт выполнен // Статус: Нейтрализован", EN: "Contract Fulfilled // Status: Neutralized" },
    authorizationReward: { RU: "Награда за авторизацию", EN: "Authorization Reward" },
    scanHighPriority: { RU: "Поиск высокоприоритетных целей", EN: "Scan for High-Priority Targets" },
    powerUnitsFee: { RU: "Сбор: 100 Ед. Энергии", EN: "Fee: 100 Power Units" },
    trustPoints: { RU: "Очки доверия", EN: "Trust Points" },
    clearanceTier: { RU: "Ранг допуска", EN: "Clearance Tier" },
    factionPerks: { RU: "Фракционные навыки", EN: "Faction Perks" },
    dossierActive: { RU: "Досье активно", EN: "Dossier Active" },
    constructionProgress: { RU: "Прогресс строительства", EN: "Construction Progress" },
    vaultCapacityIndex: { RU: "Индекс емкости хранилища", EN: "Vault Capacity Index" },
    withdraw100: { RU: "Забрать 100", EN: "Withdraw 100" },
    deposit100: { RU: "Внести 100", EN: "Deposit 100" },
    vaultEmpty: { RU: "Хранилище пусто", EN: "Vault Empty" },
    drillCargoPayload: { RU: "Груз бура", EN: "Drill Cargo Payload" },
    structuralEvolution: { RU: "Структурная эволюция", EN: "Structural Evolution" },
    upgradePath: { RU: "Путь улучшения", EN: "Upgrade Path" },
    initiatePhaseShift: { RU: "НАЧАТЬ ФАЗОВЫЙ СДВИГ", EN: "INITIATE PHASE SHIFT" },
    module_id: { RU: "ID МОДУЛЯ", EN: "MODULE ID" },
    authorizeConstruction: { RU: "РАЗРЕШИТЬ СТРОИТЕЛЬСТВО", EN: "AUTHORIZE CONSTRUCTION" },
    structuralIntegrity: { RU: "Целостность структуры", EN: "Structural Integrity" },
    auraShieldCapacity: { RU: "Мощность энергетического щита", EN: "Aura Shield Capacity" },
    compositePowerIndex: { RU: "Композитный индекс мощности", EN: "Composite Power Index" },
    queueUnitDraft: { RU: "В ОЧЕРЕДЬ СБОРКИ", EN: "QUEUE UNIT DRAFT" },
    strategicForge: { RU: "Стратегическая кузница", EN: "Strategic Forge" },
    activeProductionCycle: { RU: "Активный цикл производства", EN: "Active Production Cycle" },
    telemetryActive: { RU: "Телеметрия активна", EN: "Telemetry Active" },
    sectorSync: { RU: "Синхронизация сектора", EN: "Sector Sync" },
    synced: { RU: "Синхронизировано", EN: "Synced" },
    resourcesRequired: { RU: "Требуемые ресурсы", EN: "Resources Required" },
    yieldMatrix: { RU: "Матрица выхода", EN: "Yield Matrix" },
    x1Craft: { RU: "СОЗДАТЬ X1", EN: "X1 CRAFT" },
    maxCraft: { RU: "МАКС. КРАФТ", EN: "MAX CRAFT" },
    requiresModule: { RU: "ТРЕБУЕТСЯ МОДУЛЬ", EN: "REQUIRES MODULE" },
    baseStoredMatrix: { RU: "Матрица ресурсов базы", EN: "Base Stored Matrix" },
    empty: { RU: "Пусто", EN: "Empty" },
    xenoArchive: { RU: "КСЕНО-АРХИВ", EN: "XENO ARCHIVE" },
    accessGranted: { RU: "ДОСТУП РАЗРЕШЕН", EN: "ACCESS GRANTED" },
    databaseCoverage: { RU: "Покрытие базы данных", EN: "Database Coverage" },
    artifactsVault: { RU: "Хранилище артефактов", EN: "Artifacts Vault" },
    hostileRegistry: { RU: "Реестр угроз", EN: "Hostile Registry" },
    unknownSubstance: { RU: "Неизвестная субстанция", EN: "Unknown Substance" },
    augmentationMod: { RU: "Модификатор усиления", EN: "Augmentation Mod" },
    unknownSpectre: { RU: "Неизвестный призрак", EN: "Unknown Spectre" },
    identifiedWeakness: { RU: "Выявленная уязвимость", EN: "Identified Weakness" },
    hackLink: { RU: "КАНАЛ ВЗЛОМА", EN: "HACK LINK" },
    procedStatus: { RU: "СТАТУС ОБРАБОТКИ", EN: "PROCED STATUS" },
    tapForce: { RU: "СИЛА НАЖАТИЯ", EN: "TAP FORCE" },
    syncOnSignal: { RU: "СИНХРОНИЗИРУЙТЕ ПО СИГНАЛУ", EN: "SYNCHRONIZE ON SIGNAL" },
    lockZone: { RU: "ЗОНА БЛОКИРОВКИ", EN: "LOCK ZONE" },
    pressToEngage: { RU: "НАЖМИТЕ ДЛЯ ТЯГИ", EN: "PRESS TO ENGAGE" },
    targetSequence: { RU: "ЦЕЛЕВАЯ ПОСЛЕДОВАТЕЛЬНОСТЬ", EN: "TARGET SEQUENCE" },
    bridgeNodes: { RU: "СОЕДИНИТЕ ВНЕШНИЕ УЗЛЫ", EN: "BRIDGE NODES" },
    bufferIntegrity: { RU: "Целостность буфера", EN: "Buffer Integrity" },
    offline: { RU: "ОФФЛАЙН", EN: "OFFLINE" },
    sec: { RU: "СЕК", EN: "SEC" },

    // Табы Кузницы
    tabDrill: { RU: "БУР", EN: "DRILL" },
    tabSystems: { RU: "СИСТЕМЫ", EN: "SYSTEMS" },
    tabHull: { RU: "КОРПУС", EN: "HULL" },
    tabSupply: { RU: "СНАБЖЕНИЕ", EN: "SUPPLY" },
    tabFusion: { RU: "СИНТЕЗ", EN: "FUSION" },
    tabDrones: { RU: "ДРОНЫ", EN: "DRONES" },

    // Параметры
    paramDmg: { RU: "УРОН", EN: "DMG" },
    paramSpd: { RU: "СКОРОСТЬ", EN: "SPD" },
    paramPwr: { RU: "МОЩНОСТЬ", EN: "PWR" },
    paramCap: { RU: "ЕМКОСТЬ", EN: "CAP" },

    // Категории навыков
    skillsCortex: { RU: "ФРОНТАЛЬНАЯ КОРА", EN: "FRONTAL CORTEX" },
    skillsMotor: { RU: "ТЕМЕННАЯ ДОЛЯ", EN: "PARIETAL LOBE" },
    skillsVisual: { RU: "ЗАТЫЛОЧНАЯ ДОЛЯ", EN: "OCCIPITAL LOBE" },
    skillsChronos: { RU: "ВИСОЧНАЯ ДОЛЯ", EN: "TEMPORAL LOBE" },
    descCortex: { RU: "УПРАВЛЕНИЕ ТЕПЛОМ", EN: "HEAT CONTROL" },
    descMotor: { RU: "АВТОМАТИКА И ПРИВОД", EN: "AUTO & DRIVE" },
    descVisual: { RU: "ВОСПРИЯТИЕ И СКАН", EN: "PERCEPTION & SCAN" },
    descChronos: { RU: "ВРЕМЯ И ПРОГРЕСС", EN: "TIME & PROGRESS" },

    // Дополнительные для Рынка
    tradingTerminal: { RU: "ТОРГОВЫЙ ТЕРМИНАЛ", EN: "TRADING TERMINAL" },
    shadowExchange: { RU: "ТЕНЕВОЙ ОБМЕН", EN: "SHADOW EXCHANGE" },
    encryptedChannel: { RU: "Зашифрованный канал активен // Транзакции не отслеживаются", EN: "Encrypted Channel Active // Untraceable Transactions" },
    resourceConversion: { RU: "КОНВЕРСИЯ РЕСУРСОВ", EN: "RESOURCE CONVERSION" },
    directExchangeDesc: { RU: "Прямой обмен руды на энергетические компоненты", EN: "Direct Exchange of Raw Ores for Energy Components" },
    selectFeedstock: { RU: "1. Выберите сырье", EN: "1. Select Feedstock" },
    finalizeExchange: { RU: "2. Завершить обмен", EN: "2. Finalize Exchange" },
    yieldEstimate: { RU: "Оценка выхода", EN: "Yield Estimate" },
    transaction: { RU: "ТРАНЗАКЦИЯ", EN: "TRANSACTION" },
    stock: { RU: "Запас", EN: "Stock" },
    totalExpense: { RU: "Общие расходы", EN: "Total Expense" },
    netRevenue: { RU: "Чистая прибыль", EN: "Net Revenue" },
    awaitingSignal: { RU: "Ожидание сигнала выбора", EN: "Awaiting Selection Signal" },
    terminalStatusOnline: { RU: "Статус терминала: В сети // Опасные зоны активны", EN: "Terminal Status: Online // Unsafe Zones Active" },
    exchange: { RU: "ОБМЕН", EN: "EXCHANGE" },
    junkDealer: { RU: "СКУПЩИК УТИЛЯ", EN: "JUNK DEALER" },
    insufficientResources: { RU: "НЕДОСТАТОЧНО РЕСУРСОВ", EN: "INSUFFICIENT RESOURCES" },
    fuelStation: { RU: "ЗАПРАВКА ТОПЛИВОМ", EN: "FUEL STATION" },
    dealerAccepts: { RU: "Скупщик принимает любые ресурсы: 10 шт → 5 угля", EN: "Dealer accepts any resources: 10 units → 5 coal" },
    inStock: { RU: "В НАЛИЧИИ", EN: "IN STOCK" },
    industrialCrusher: { RU: "ПРОМЫШЛЕННАЯ ДРОБИЛКА", EN: "INDUSTRIAL CRUSHER" },
    start: { RU: "ЗАПУСК", EN: "START" },
    barRustyNut: { RU: 'БАР "РЖАВАЯ ГАЙКА"', EN: 'BAR "RUSTY NUT"' },
    barTagline: { RU: '"Наши напитки не просто сшибают с ног, они разъедают пол."', EN: '"Our drinks don\'t just knock you off your feet, they eat through the floor."' },
    gamblingZone: { RU: "ЗОНА ЛУДОМАНОВ", EN: "GAMBLING ZONE" },
    gamblingTagline: { RU: '"Где горы камня превращаются в пыль... или в кредиты."', EN: '"Where mountains of stone turn to dust... or credits."' },
    voidDice: { RU: "КОСТЬ ПУСТОТЫ", EN: "VOID DICE" },
    diceDesc: { RU: "Классическая игра на удачу. Попробуй удвоить свои ресурсы.", EN: "Classic game of luck. Try to double your resources." },
    chance45: { RU: "45% шанс", EN: "45% chance" },
    payoutX2: { RU: "Выплата x2 (Чистая прибыль x1)", EN: "Payout x2 (Net profit x1)" },
    seismicRoulette: { RU: "СЕЙСМО-РУЛЕТКА", EN: "SEISMIC ROULETTE" },
    rouletteDesc: { RU: "Экстремальная лотерея для тех, у кого полные склады камня.", EN: "Extreme lottery for those with full warehouses of stone." },
    chance5: { RU: "5% общий шанс", EN: "5% total chance" },
    roulettePrizes: { RU: "Кредиты (1.5-5.0%), или x5 Камня", EN: "Credits (1.5-5.0%), or x5 Stone" },
    fuelShells: { RU: "ТОПЛИВНЫЕ НАПЁРСТКИ", EN: "FUEL SHELLS" },
    shellsDesc: { RU: "Рискни глиной, чтобы добыть ценное газовое топливо.", EN: "Risk clay to get valuable gas fuel." },
    gas10Units: { RU: "10 единиц ГАЗА", EN: "10 units of GAS" },
    voidSlots: { RU: "СЛОТ-МАШИНА 'БЕЗДНА'", EN: "VOID SLOTS" },
    slotsDesc: { RU: "Конвертация излишков железа в твердую валюту.", EN: "Convert excess iron into hard currency." },
    credits20: { RU: "20 КРЕДИТОВ", EN: "20 CREDITS" },
    vipLounge: { RU: "ЗАКРЫТЫЙ ЛОНДЖ", EN: "VIP LOUNGE" },
    vipTagline: { RU: "Для тех, кто не считает кредиты", EN: "For those who don't count credits" },
    balance_label: { RU: "БАЛАНС", EN: "BALANCE" },
    bribeManagement: { RU: "ПОДКУП РУКОВОДСТВА", EN: "BRIBE MANAGEMENT" },
    bribeDesc: { RU: '"Взнос" в фонд станции в обмен на ускоренную сертификацию.', EN: '"Donation" to the station fund in exchange for accelerated certification.' },
    success35: { RU: "35% Суммарно", EN: "35% Total" },
    prize3kXP: { RU: "до 3к XP", EN: "up to 3k XP" },
    blackTender: { RU: "ЧЕРНЫЙ ТЕНДЕР", EN: "BLACK TENDER" },
    tenderDesc: { RU: "Покупка прав на вскрытие неопознанного контейнера.", EN: "Purchase of rights to open an unidentified container." },
    chance100Artifact: { RU: "100% АРТЕФАКТ", EN: "100% ARTIFACT" },
    rarity88Common: { RU: "88% БЕЛЫЕ", EN: "88% COMMON" },
    bet_label: { RU: "СТАВКА", EN: "BET" },
    deal_btn: { RU: "ЗАКЛЮЧИТЬ ПАРИ", EN: "DEAL" },
    win_label: { RU: "ПОБЕДА!", EN: "WIN!" },
    loss_label: { RU: "НЕ УДАЧА", EN: "LUCKLESS" },
    transactionResult: { RU: "РЕЗУЛЬТАТ ТРАНЗАКЦИИ:", EN: "TRANSACTION RESULT:" },
    acceptFate: { RU: "ПРИНЯТЬ ТАКУЮ СУДЬБУ", EN: "ACCEPT THIS FATE" },
    menu_label: { RU: "МЕНЮ", EN: "MENU" },
    gamble_label: { RU: "АЗАРТ", EN: "GAMBLE" },
    vipClub_label: { RU: "VIP КЛУБ", EN: "VIP CLUB" },
    cooldown_label: { RU: "КУЛДАУН", EN: "COOLDOWN" },
    available_in: { RU: "ДОСТУПНО ЧЕРЕЗ", EN: "AVAILABLE IN" },
    success_label: { RU: "Успех", EN: "Success" },
    prize_label: { RU: "Приз", EN: "Prize" },
    chance_label: { RU: "Шанс", EN: "Chance" },
    rarity_label: { RU: "Редкость", EN: "Rarity" },
    prizes_label: { RU: "Призы", EN: "Prizes" },
    waiting: { RU: "ОЖИДАНИЕ", EN: "WAITING" },
    coolingSystem: { RU: "СИСТЕМА ОХЛАЖДЕНИЯ", EN: "COOLING SYSTEM" },
    currentHeat: { RU: "ТЕКУЩИЙ НАГРЕВ", EN: "CURRENT HEAT" },
    free_label: { RU: "БЕСПЛАТНО", EN: "FREE" },
    systemNormal: { RU: "СИСТЕМА В НОРМЕ", EN: "SYSTEM NORMAL" },
    emergencyPurge: { RU: "ЭКСТРЕННЫЙ СБРОС ТЕПЛА", EN: "EMERGENCY HEAT PURGE" },
    repairDock: { RU: "РЕМОНТНЫЙ ДОК", EN: "REPAIR DOCK" },
    hullIntegrity: { RU: "ЦЕЛОСТНОСТЬ ОБШИВКИ", EN: "HULL INTEGRITY" },
    fullRepair: { RU: "ПОЛНЫЙ РЕМОНТ", EN: "FULL REPAIR" },
    noDamage: { RU: "ПОВРЕЖДЕНИЙ НЕТ", EN: "NO DAMAGE" },
    restoreHull: { RU: "ВОССТАНОВИТЬ ОБШИВКУ", EN: "RESTORE HULL" },
    premiumService: { RU: "ПРЕМИУМ ОБСЛУЖИВАНИЕ", EN: "PREMIUM SERVICE" },
    fox_name: { RU: "Лиса", EN: "The Fox" },
    fox_dialogue_intro: { RU: "Ищешь Лису? Ты её нашёл. Надеюсь, ты здесь по делу, а не просто пришёл выпить.", EN: "Looking for Fox? You found her. Hope you're here for business, not just a drink." },
    fox_dialogue_market: { RU: "Теневой терминал в разделе торговли — это моя работа. Там ты найдёшь контрабанду и спецзаказы. Не попадись законникам.", EN: "The shadow terminal in the trade section is my doing. You'll find smuggling and special orders there. Don't get caught by the law." },

    // Подсистемы
    drillBit: { RU: "БУРОВАЯ КОРОНКА", EN: "DRILL BIT" },
    engine: { RU: "ДВИГАТЕЛЬ", EN: "ENGINE" },
    logicCore: { RU: "ЛОГИЧЕСКОЕ ЯДРО", EN: "LOGIC CORE" },
    controlUnit: { RU: "БЛОК УПРАВЛЕНИЯ", EN: "CONTROL UNIT" },
    cargoBay: { RU: "ГРУЗОВОЙ ОТСЕК", EN: "CARGO BAY" },
    gearbox: { RU: "КОРОБКА ПЕРЕДАЧ", EN: "GEARBOX" },
    shield: { RU: "ГЕНЕРАТОР ЩИТА", EN: "SHIELD GENERATOR" },
    structuralHull: { RU: "КОРПУС", EN: "STRUCTURAL HULL" },
    powerCore: { RU: "ЭНЕРГОБЛОК", EN: "POWER CORE" },
    armorPlating: { RU: "БРОНЕПЛАСТИНЫ", EN: "ARMOR PLATING" },

    // Характеристики и статусы чертежей
    statDmg: { RU: "УРОН", EN: "DMG" },
    statSpd: { RU: "СКОР", EN: "SPD" },
    statCool: { RU: "ОХЛ", EN: "COOL" },
    statPwr: { RU: "МОЩ", EN: "PWR" },
    statReg: { RU: "РЕГ", EN: "REG" },
    statCrg: { RU: "ГРЗ", EN: "CRG" },
    statEnergy: { RU: "ЭНГ", EN: "NRG" },
    schematicLoaded: { RU: "ЧЕРТЕЖ ЗАГРУЖЕН", EN: "SCHEMATIC LOADED" },
    fusionLocked: { RU: "ЗАБЛОКИРОВАНО (СИНТЕЗ)", EN: "FUSION LOCKED" },
    unavailable: { RU: "НЕДОСТУПНО", EN: "UNAVAILABLE" },
    inactive: { RU: "НЕ АКТИВЕН", EN: "INACTIVE" },
    assemble: { RU: "СОБРАТЬ", EN: "ASSEMBLE" },
    upgrade: { RU: "УЛУЧШИТЬ", EN: "UPGRADE" },
    next: { RU: "СЛЕД:", EN: "NEXT:" },
    ready: { RU: "ГОТОВО", EN: "READY" }
  },
  resources: {
    coal: { RU: "Уголь", EN: "Coal" },
    iron: { RU: "Железо", EN: "Iron" },
    copper: { RU: "Медь", EN: "Copper" },
    gold: { RU: "Золото", EN: "Gold" },
    oil: { RU: "Нефть", EN: "Oil" },
    uranium: { RU: "Уран", EN: "Uranium" },
    diamonds: { RU: "Алмазы", EN: "Diamonds" },
    ancientTech: { RU: "Древние Технологии", EN: "Ancient Tech" },
    nanoSwarm: { RU: "Нано-Рой", EN: "Nano-Swarm" },
    stone: { RU: "Камень", EN: "Stone" },
    clay: { RU: "Глина", EN: "Clay" },
    gas: { RU: "Газ", EN: "Gas" },
    XP: { RU: "Опыт", EN: "XP" },
    rubies: { RU: "Рубины", EN: "Rubies" },
    emeralds: { RU: "Изумруды", EN: "Emeralds" },
    silver: { RU: "Серебро", EN: "Silver" },
    titanium: { RU: "Титан", EN: "Titanium" },
    ice: { RU: "Лёд", EN: "Ice" },
    scrap: { RU: "Металлолом", EN: "Scrap" },
    repairKit: { RU: "Ремкомплект", EN: "Repair Kit" },
    coolantPaste: { RU: "Охлаждающая паста", EN: "Coolant Paste" },
    advancedCoolant: { RU: "Активный хладагент", EN: "Active Coolant" },
    voidMatter: { RU: "Материя Пустоты", EN: "Void Matter" },
    chronoShards: { RU: "Хроно-осколки", EN: "Chrono-Shards" },
    credits: { RU: "Кредиты", EN: "Credits" }
  },
  caravan: {
    title: { RU: "КАРАВАННАЯ ЛОГИСТИКА", EN: "CARAVAN LOGISTICS" },
    subtitle: { RU: "Транспортировка ресурсов между базами", EN: "Transporting resources between bases" },
    send: { RU: "Отправить Караван", EN: "Send Caravan" },
    capacity: { RU: "Вместимость", EN: "Capacity" },
    risk: { RU: "Риск", EN: "Risk" },
    duration: { RU: "Время", EN: "Duration" },
    status: {
      idle: { RU: "Ожидание", EN: "Idle" },
      in_transit: { RU: "В пути", EN: "In Transit" },
      returning: { RU: "Возвращается", EN: "Returning" }
    }
  },
  factions: {
    title: { RU: "Фракции", EN: "Factions" },
    names: {
      CORPORATE: { RU: "Void Industries", EN: "Void Industries" },
      SCIENCE: { RU: "Aegis Collegium", EN: "Aegis Collegium" },
      REBELS: { RU: "Свободные Шахтеры", EN: "Free Miners" }
    },
    descriptions: {
      CORPORATE: { RU: "Мега-корпорация, контролирующая логистику и права на добычу.", EN: "Mega-corporation controlling logistics and mining rights." },
      SCIENCE: { RU: "Научный орден, изучающий Пустоту и древние артефакты.", EN: "Scientific order studying the Void and ancient artifacts." },
      REBELS: { RU: "Независимые шахтеры, борющиеся за свободу от корпоративного контроля.", EN: "Independent miners fighting for freedom from corporate control." }
    },
    perks: {
      CORP_EXCHANGE: { name: { RU: "Корпоративный обмен", EN: "Corporate Exchange" }, description: { RU: "Цены на рынке снижены на 5%", EN: "Market prices reduced by 5%" } },
      BULK_LOGISTICS: { name: { RU: "Массовая логистика", EN: "Bulk Logistics" }, description: { RU: "Вместимость караванов увеличена на 20%", EN: "Caravan capacity increased by 20%" } },
      INSURANCE: { name: { RU: "Страхование грузов", EN: "Cargo Insurance" }, description: { RU: "Риск потери каравана снижен на 50%", EN: "Caravan loss risk reduced by 50%" } },
      EXECUTIVE: { name: { RU: "Исполнительный доступ", EN: "Executive Access" }, description: { RU: "Пассивная генерация ресурсов x2", EN: "Passive resource generation x2" } },
      RESEARCH_GRANT: { name: { RU: "Научные гранты", EN: "Research Grants" }, description: { RU: "Стоимость продажи артефактов +10%", EN: "Artifact sale value +10%" } },
      AUTO_ANALYSIS: { name: { RU: "Авто-анализ", EN: "Auto-Analysis" }, description: { RU: "Время анализа артефактов снижено на 25%", EN: "Artifact analysis time reduced by 25%" } },
      ANOMALY_SCANNER: { name: { RU: "Сканер аномалий", EN: "Anomaly Scanner" }, description: { RU: "Раскрывает уровень риска в туннелях", EN: "Reveals risk levels in tunnels" } },
      QUANTUM_STABILITY: { name: { RU: "Квантовая стабильность", EN: "Quantum Stability" }, description: { RU: "Частота тектонических событий снижена на 50%", EN: "Tectonic event frequency reduced by 50%" } },
      BLACK_MARKET: { name: { RU: "Черный рынок", EN: "Black Market" }, description: { RU: "Открывает торговлю нелегальными товарами", EN: "Unlocks black market trade" } },
      SMUGGLER: { name: { RU: "Контрабандист", EN: "Smuggler" }, description: { RU: "Расход топлива снижен на 20%", EN: "Fuel consumption reduced by 20%" } },
      SABOTAGE: { name: { RU: "Саботаж", EN: "Sabotage" }, description: { RU: "Шанс успеха в опасных туннелях +10%", EN: "Success chance in dangerous tunnels +10%" } },
      LIBERATION: { name: { RU: "Герой освобождения", EN: "Liberation Hero" }, description: { RU: "Эффективность защиты базы +50%", EN: "Base defense efficiency +50%" } }
    },
    standing: { RU: "Текущий статус", EN: "Current Standing" },
    reputation: { RU: "Репутация", EN: "Reputation" },
    nextTier: { RU: "След. уровень", EN: "Next Tier" },
    max: { RU: "МАКС", EN: "MAX" },
    perkTitle: { RU: "Фракционные навыки", EN: "Faction Perks" },
    rivalry: { RU: "ВРАЖДА: Повышение репутации здесь снижает отношения с", EN: "RIVALRY: Increasing reputation here reduces relations with" },
    rivalryWarning: { RU: "ПРОТИВОСТОЯНИЕ", EN: "CONFRONTATION" }
  },
  quests: {
    title: { RU: "Центр Контрактов", EN: "Contract Center" },
    tabs: {
      available: { RU: "Доступные", EN: "Available" },
      active: { RU: "Активные", EN: "Active" },
      completed: { RU: "Завершенные", EN: "Completed" }
    },
    accept: { RU: "ПРИНЯТЬ КОНТРАКТ", EN: "ACCEPT CONTRACT" },
    complete: { RU: "ЗАВЕРШИТЬ", EN: "COMPLETE" },
    rewards: { RU: "Награды", EN: "Rewards" },
    ready: { RU: "ГОТОВО", EN: "READY" },
    noAvailable: { RU: "Нет доступных контрактов. Выполните текущие или исследуйте мир.", EN: "No contracts available. Complete current ones or explore the world." },
    noActive: { RU: "Нет активных квестов.", EN: "No active quests." },
    emptyHistory: { RU: "История пуста.", EN: "History is empty." },
    completedStatus: { RU: "ЗАВЕРШЕНО", EN: "COMPLETED" }
  },
  weaknesses: {
    MASH: { RU: "СПАМ КЛИКОВ", EN: "CLICK MASH" },
    ALIGN: { RU: "ВЫРАВНИВАНИЕ", EN: "ALIGNMENT" },
    TIMING: { RU: "ТАЙМИНГ", EN: "TIMING" },
    MEMORY: { RU: "ПАМЯТЬ", EN: "MEMORY" }
  }
};

// Локализованные текстовые строки с поддержкой RU/EN
export const TEXT_IDS = {
  // Меню и навигация
  SETTINGS_TITLE: { RU: 'НАСТРОЙКИ', EN: 'SETTINGS' },
  SETTINGS_BUTTON: { RU: 'НАСТРОЙКИ', EN: 'SETTINGS' },
  MANUAL_BUTTON: { RU: 'РУКОВОДСТВО', EN: 'MANUAL' },
  EXIT_BUTTON: { RU: 'ВЫХОД', EN: 'EXIT' },
  MENU_DRILL: { RU: 'БУР', EN: 'DRILL' },
  MENU_CITY: { RU: 'ГОРОД', EN: 'CITY' },
  MENU_FORGE: { RU: 'КУЗНИЦА', EN: 'FORGE' },
  MENU_SKILLS: { RU: 'НАВЫКИ', EN: 'SKILLS' },
  MENU_ARTIFACTS: { RU: 'АРТЕФАКТЫ', EN: 'ARTIFACTS' },
  MENU_MAP: { RU: 'КАРТА', EN: 'MAP' },
  MENU_ARCHIVE: { RU: 'АРХИВ', EN: 'ARCHIVE' },

  // Заголовки разделов
  HEADER_RARE_RESOURCES: { RU: 'РЕДКИЕ / ЦЕННЫЕ', EN: 'RARE / PRECIOUS' },
  ARCHIVE_TITLE: { RU: 'АРХИВ ЭКСПЕДИЦИЙ', EN: 'EXPEDITION ARCHIVE' },
  COLLECTION_STATUS: { RU: 'СТАТУС КОЛЛЕКЦИИ', EN: 'COLLECTION STATUS' },
  UNKNOWN_ITEM: { RU: 'НЕИЗВЕСТНО', EN: 'UNKNOWN' },
  LOCKED_ITEM: { RU: 'ЗАБЛОКИРОВАНО', EN: 'LOCKED' },

  // Городские службы
  CITY_COOLING_SYSTEM: { RU: 'СИСТЕМА ОХЛАЖДЕНИЯ', EN: 'COOLING SYSTEM' },
  CITY_REPAIR_DOCK: { RU: 'РЕМОНТНЫЙ ДОК', EN: 'REPAIR DOCK' },
  CITY_PREMIUM_SERVICE: { RU: 'ПРЕМИУМ ОБСЛУЖИВАНИЕ', EN: 'PREMIUM SERVICE' },
  CITY_LICENSES: { RU: 'ЛИЦЕНЗИОННЫЙ ЦЕНТР', EN: 'LICENSE CENTER' },
  CITY_CURRENT_HEAT: { RU: 'ТЕКУЩИЙ НАГРЕВ', EN: 'CURRENT HEAT' },
  CITY_HULL_INTEGRITY: { RU: 'ЦЕЛОСТНОСТЬ ОБШИВКИ', EN: 'HULL INTEGRITY' },
  CITY_COST: { RU: 'СТОИМОСТЬ', EN: 'COST' },
  CITY_FULL_REPAIR: { RU: 'ПОЛНЫЙ РЕМОНТ', EN: 'FULL REPAIR' },
  CITY_REPAIR_BTN: { RU: 'ВОССТАНОВИТЬ ОБШИВКУ', EN: 'REPAIR HULL' },
  CITY_COOLING_BTN: { RU: 'ЭКСТРЕННЫЙ СБРОС ТЕПЛА', EN: 'EMERGENCY HEAT PURGE' },
  CITY_FREE: { RU: 'БЕСПЛАТНО', EN: 'FREE' },
  CITY_NO_DAMAGE: { RU: 'ПОВРЕЖДЕНИЙ НЕТ', EN: 'NO DAMAGE' },
  CITY_SYSTEM_OK: { RU: 'СИСТЕМА В НОРМЕ', EN: 'SYSTEM OK' },
  CITY_LICENSE_ZONE: { RU: 'ЛИЦЕНЗИЯ ЗОНЫ', EN: 'ZONE LICENSE' },
  CITY_PERMIT_REGION: { RU: 'РАЗРЕШЕНИЕ РЕГИОНА', EN: 'REGION PERMIT' },
  CITY_OWNED: { RU: 'КУПЛЕНО', EN: 'OWNED' },
  CITY_REQUIREMENT: { RU: 'ТРЕБУЕТСЯ', EN: 'REQUIRED' },
  CITY_PERMANENT: { RU: 'БЕССРОЧНО', EN: 'PERMANENT' },
  CITY_TEMPORARY: { RU: 'ВРЕМЕННО (7Д)', EN: 'TEMPORARY (7D)' },

  // Системные логи
  LOG_INSUFFICIENT_RESOURCES: { RU: 'НЕДОСТАТОЧНО РЕСУРСОВ', EN: 'INSUFFICIENT RESOURCES' },
  LOG_EFFECT_ACTIVATED: { RU: 'ЭФФЕКТ', EN: 'EFFECT' },
  LOG_GAMBLE_WIN: { RU: 'ВЫИГРЫШ!', EN: 'WIN!' },
  LOG_GAMBLE_LOSS: { RU: 'ПРОИГРЫШ...', EN: 'LOSS...' },
  LOG_CRAFT_SUCCESS: { RU: 'СОЗДАНО', EN: 'CRAFTED' },
  LOG_SYSTEM_RESTORED: { RU: 'СИСТЕМА ВОССТАНОВЛЕНА', EN: 'SYSTEM RESTORED' },
  LOG_PROGRESS_SAVED: { RU: 'ПРОГРЕСС ЗАПИСАН В ЧЕРНЫЙ ЯЩИК', EN: 'PROGRESS SAVED TO BLACK BOX' },
  LOG_SAVE_ERROR: { RU: 'ОШИБКА ЗАПИСИ ДАННЫХ', EN: 'DATA SAVE ERROR' },

  // Настройки аудио
  MUSIC_VOLUME: { RU: 'МУЗЫКА', EN: 'MUSIC' },
  SFX_VOLUME: { RU: 'ЗВУКИ', EN: 'SFX' },
  DRILL_VOLUME: { RU: 'БУР И МОТОР', EN: 'DRILL & MOTOR' },

  // Сброс прогресса
  RESET_PROGRESS: { RU: 'СБРОСИТЬ ПРОГРЕСС', EN: 'RESET PROGRESS' },
  RESET_CONFIRM_TITLE: { RU: 'ПОДТВЕРЖДЕНИЕ', EN: 'CONFIRMATION' },
  RESET_CONFIRM_BODY: { RU: 'Все данные будут удалены навсегда. Это действие необратимо!', EN: 'All data will be permanently deleted. This action cannot be undone!' },

  // Кнопки
  BTN_OK: { RU: 'ОК', EN: 'OK' },
  BTN_CANCEL: { RU: 'ОТМЕНА', EN: 'CANCEL' },
  BTN_DATA_BACKUP: { RU: 'РЕЗЕРВНОЕ КОПИРОВАНИЕ', EN: 'DATA BACKUP' },
  BTN_COPY_CLIPBOARD: { RU: 'СКОПИРОВАТЬ В БУФЕР', EN: 'COPY TO CLIPBOARD' },
  BTN_APPLY_CODE: { RU: 'ПРИМЕНИТЬ КОД', EN: 'APPLY CODE' },

  // Справка
  HELP_SECTION_SAVE_TITLE: { RU: 'СОХРАНЕНИЕ', EN: 'SAVING' },
  HELP_SECTION_SAVE_BODY: { RU: 'Игра НЕ сохраняется автоматически. Используйте кнопку "ЗАПИСЬ" в настройках.', EN: 'The game does NOT auto-save. Use the "SAVE" button in settings.' },
  HELP_SECTION_EXPORT_TITLE: { RU: 'ЭКСПОРТ/ИМПОРТ', EN: 'EXPORT/IMPORT' },
  HELP_SECTION_EXPORT_BODY: { RU: 'Вы можете экспортировать сохранение как текстовый код и импортировать его позже.', EN: 'You can export your save as a text code and import it later.' },

  // Начальный экран / AI
  AI_INIT: { RU: 'ИНИЦИАЛИЗАЦИЯ СИСТЕМЫ...', EN: 'INITIALIZING SYSTEM...' },
  AI_READY: { RU: 'СИСТЕМА ГОТОВА', EN: 'SYSTEM READY' },
  HARDCORE_WARNING: { RU: '⚠️ ВНИМАНИЕ: Прогресс НЕ сохраняется автоматически!', EN: '⚠️ WARNING: Progress is NOT auto-saved!' },
  INIT_BUTTON: { RU: 'НАЧАТЬ СПУСК', EN: 'BEGIN DESCENT' },
  FIRST_RUN_TITLE: { RU: 'ПЕРВЫЙ ЗАПУСК', EN: 'FIRST RUN' },
  FIRST_RUN_BODY: { RU: 'Добро пожаловать в Пустоту. Это хардкорный опыт без автосохранения. Удачи.', EN: 'Welcome to the Void. This is a hardcore experience without auto-save. Good luck.' },
  BTN_ACKNOWLEDGE: { RU: 'ПОНЯЛ', EN: 'UNDERSTOOD' },

  // Дополнительные строки для настроек
  SETTINGS_BLACK_BOX: { RU: 'ЧЕРНЫЙ ЯЩИК', EN: 'BLACK BOX' },
  SETTINGS_MANUAL_MEM: { RU: 'РУЧНОЕ УПРАВЛЕНИЕ ПАМЯТЬЮ', EN: 'MANUAL MEMORY CONTROL' },
  SETTINGS_SAVE_BTN: { RU: '[ ЗАПИСЬ ]', EN: '[ RECORD ]' },
  SETTINGS_SAVE_SUB: { RU: 'СОХРАНИТЬ ТЕКУЩЕЕ', EN: 'SAVE CURRENT' },
  SETTINGS_LOAD_BTN: { RU: '[ ЧТЕНИЕ ]', EN: '[ READ ]' },
  SETTINGS_LOAD_SUB: { RU: 'ЗАГРУЗИТЬ ПОСЛЕДНЕЕ', EN: 'LOAD LATEST' },
  SETTINGS_SAVE_WARNING: { RU: 'ВНИМАНИЕ: ПРОГРЕСС НЕ СОХРАНЯЕТСЯ АВТОМАТИЧЕСКИ.', EN: 'WARNING: PROGRESS IS NOT AUTO-SAVED.' },
  SETTINGS_BACKUP_TITLE: { RU: 'РЕЗЕРВНОЕ КОПИРОВАНИЕ', EN: 'DATA BACKUP' },
  SETTINGS_CODE_LABEL: { RU: 'КОД (BASE64)', EN: 'CODE (BASE64)' },
  SETTINGS_RESTORE_LABEL: { RU: 'ВОССТАНОВЛЕНИЕ', EN: 'RESTORE' },
  SETTINGS_IMPORT_PLACEHOLDER: { RU: 'Вставьте код сохранения...', EN: 'Paste save code here...' },
  SETTINGS_APPLY_CODE: { RU: 'ПРИМЕНИТЬ КОД', EN: 'APPLY CODE' },
  SETTINGS_COPY_CLIPBOARD: { RU: 'СКОПИРОВАТЬ В БУФЕР', EN: 'COPY TO CLIPBOARD' },

  // Уведомления настроек
  MSG_COPIED: { RU: 'СКОПИРОВАНО В БУФЕР!', EN: 'COPIED TO CLIPBOARD!' },
  MSG_EXPORT_ERROR: { RU: 'ОШИБКА ЭКСПОРТА', EN: 'EXPORT ERROR' },
  MSG_IMPORT_ERROR: { RU: 'НЕВЕРНЫЙ ФОРМАТ СОХРАНЕНИЯ', EN: 'INVALID SAVE FORMAT' },
  MSG_DATA_SAVED: { RU: 'ДАННЫЕ ЗАПИСАНЫ', EN: 'DATA RECORDED' },
  MSG_DATA_LOADED: { RU: 'ДАННЫЕ ЗАГРУЖЕНЫ', EN: 'DATA LOADED' },
  MSG_NO_DATA: { RU: 'НЕТ ДАННЫХ ДЛЯ ЗАГРУЗКИ', EN: 'NO DATA TO LOAD' },
  LABEL_EFFECT: { RU: 'ЭФФЕКТ:', EN: 'EFFECT:' },
  AI_ERROR: { RU: '[ ОШИБКА ]', EN: '[ ERROR ]' },
  AI_CORE_LABEL: { RU: 'ИИ-ЯДРО', EN: 'AI-CORE' },

  // Fusion System
  FORGE_FUSION: { RU: 'СЛИЯНИЕ', EN: 'FUSION' },
  FUSION_TITLE: { RU: 'СИНТЕЗ ДЕТАЛЕЙ', EN: 'PART FUSION' },
  FUSION_DESCRIPTION: { RU: 'Объедините две детали одного типа для создания улучшенной версии', EN: 'Combine two parts of the same type to create an improved version' },
  FUSION_CONDITION_ZERO_HEAT: { RU: 'Нулевой нагрев', EN: 'Zero Heat' },
  FUSION_CONDITION_MAX_HEAT: { RU: 'Максимальный нагрев', EN: 'Max Heat' },
  FUSION_CONDITION_DEPTH: { RU: 'Глубина', EN: 'Depth' },
  FUSION_CONDITION_NO_DAMAGE: { RU: 'Без повреждений', EN: 'No Damage' },
  FUSION_CATALYST: { RU: 'Катализатор', EN: 'Catalyst' },
  FUSION_COMPONENTS: { RU: 'Компоненты', EN: 'Components' },
  FUSION_RESULT: { RU: 'Результат', EN: 'Result' },
  FUSION_BUTTON: { RU: 'СЛИТЬ', EN: 'FUSE' },
  FUSION_REQUIREMENTS: { RU: 'Требования', EN: 'Requirements' },
  FUSION_CONDITION_MET: { RU: 'Выполнено', EN: 'Met' },
  FUSION_CONDITION_NOT_MET: { RU: 'Не выполнено', EN: 'Not Met' },
  FUSION_NO_RECIPES: { RU: 'Нет доступных рецептов слияния', EN: 'No fusion recipes available' },
  FUSION_SUCCESS: { RU: 'Слияние успешно!', EN: 'Fusion successful!' },
  FUSION_FAILED: { RU: 'Слияние не удалось', EN: 'Fusion failed' },

  // Transmutation
  TRANSMUTATION_TITLE: { RU: 'ТРАНСМУТАЦИЯ', EN: 'TRANSMUTATION' },
  TRANSMUTATION_DESC: { RU: 'Выберите 3 артефакта одной редкости, чтобы получить 1 более редкий.', EN: 'Select 3 artifacts of the same rarity to get 1 rarer artifact.' },
  TRANSMUTATION_BUTTON: { RU: 'ЗАПУСК СИНТЕЗА', EN: 'START SYNTHESIS' },
  TRANSMUTATION_NO_ARTIFACTS: { RU: 'НЕТ ДОСТУПНЫХ АРТЕФАКТОВ', EN: 'NO AVAILABLE ARTIFACTS' },

  // Fusion Tab
  FUSION_ATOMIC_RECONSTRUCTOR: { RU: 'АТОМНЫЙ РЕКОНСТРУКТОР', EN: 'ATOMIC RECONSTRUCTOR' },
  FUSION_REQUIRED: { RU: 'ТРЕБУЕТСЯ:', EN: 'REQUIRED:' },
  FUSION_STATUS: { RU: 'СТАТУС:', EN: 'STATUS:' },
  FUSION_COMPLETED: { RU: 'ВЫПОЛНЕНО', EN: 'COMPLETED' },
  FUSION_HULL_DAMAGED: { RU: 'ОБШИВКА ПОВРЕЖДЕНА', EN: 'HULL DAMAGED' },
  FUSION_PREVIOUS_TIER_REQUIRED: { RU: 'ПРЕДЫДУЩИЙ ТИР', EN: 'PREVIOUS TIER' },
  FUSION_ALREADY_UPGRADED: { RU: 'УЖЕ УЛУЧШЕНО', EN: 'ALREADY UPGRADED' },
  FUSION_INSTALLED: { RU: 'УСТАНОВЛЕНО', EN: 'INSTALLED' },
  FUSION_SYNTHESIZE: { RU: 'СИНТЕЗИРОВАТЬ', EN: 'SYNTHESIZE' },
  FUSION_UNAVAILABLE: { RU: 'НЕДОСТУПНО', EN: 'UNAVAILABLE' },

  // Системные настройки (технические термины)
  SETTINGS_CONFIG_TITLE: { RU: "КОНФИГУРАЦИЯ СИСТЕМЫ", EN: "SYSTEM CONFIGURATION" },
  SETTINGS_LOCALIZATION_BUS: { RU: "ШИНА ЛОКАЛИЗАЦИИ", EN: "LOCALIZATION BUS" },
  SETTINGS_GRAPHICS_RENDERER: { RU: "ГРАФИЧЕСКИЙ РЕНДЕРЕР", EN: "GRAPHICS RENDERER" },
  SETTINGS_INTERNAL_BYPASS: { RU: "ВНУТРЕННИЙ ОБХОД", EN: "INTERNAL BYPASS" },
  SETTINGS_BTN_DEV_CONSOLE: { RU: "ОТКРЫТЬ КОНСОЛЬ РАЗРАБОТЧИКА", EN: "OPEN DEV CONSOLE" },
  SETTINGS_PLACEHOLDER_ACCESS_CODE: { RU: "КОД ДОСТУПА", EN: "ACCESS CODE" },
  SETTINGS_BTN_VERIFY: { RU: "ПРОВЕРИТЬ", EN: "VERIFY" },
  SETTINGS_AUDIO_MIXER: { RU: "ПОДСИСТЕМА АУДИО-МИКШЕРА", EN: "AUDIO MIXER SUBSYSTEM" },
  SETTINGS_STATUS_MUTED: { RU: "ОТКЛЮЧЕНО", EN: "MUTED" },
  SETTINGS_STATUS_ONLINE: { RU: "В СЕТИ", EN: "ONLINE" },
  SETTINGS_BUILD_REVISION: { RU: "РЕВИЗИЯ СБОРКИ", EN: "BUILD REVISION" },

  // Logbook
  LOGBOOK_TITLE: { RU: 'БОРТОВОЙ ЖУРНАЛ', EN: 'SHIP LOG' },
  LOGBOOK_TAB_LOGS: { RU: 'ЛОГИ', EN: 'LOGS' },
  LOGBOOK_TAB_COMM: { RU: 'СВЯЗЬ', EN: 'COMM LINK' },
  LOGBOOK_TAB_MISSIONS: { RU: 'МИССИИ', EN: 'MISSIONS' },
  LOGBOOK_ACTIVE_MISSIONS: { RU: 'АКТИВНЫЕ КОНТРАКТЫ', EN: 'ACTIVE CONTRACTS' },
  LOGBOOK_COMPLETED_MISSIONS: { RU: 'АРХИВ КОНТРАКТОВ', EN: 'CONTRACT ARCHIVE' },
  LOGBOOK_ACTIVE_ASSEMBLIES: { RU: 'АКТИВНЫЕ СБОРКИ', EN: 'ACTIVE ASSEMBLIES' },
  LOGBOOK_NO_ENTRIES: { RU: 'НЕТ ЗАПИСЕЙ', EN: 'NO ENTRIES FOUND' },
  LOGBOOK_EMPTY_BUFFER: { RU: 'Буфер данных пуст', EN: 'Data buffer is empty' }
} as const;




// Тип для ключей TEXT_IDS
type TextIdKey = keyof typeof TEXT_IDS;
export type Language = 'RU' | 'EN';

// Функция локализации с поддержкой языка
export const t = (textId: { RU: string; EN: string } | string | undefined | null, lang: Language = 'RU'): string => {
  if (!textId) return '';
  // Если это простая строка и она является ключом в TEXT_IDS, возвращаем перевод
  if (typeof textId === 'string' && textId in TEXT_IDS) {
    return (TEXT_IDS as any)[textId][lang] || (TEXT_IDS as any)[textId].RU || '';
  }
  // Если это простая строка, возвращаем как есть
  if (typeof textId === 'string') return textId;
  // Если это объект с локализацией, возвращаем нужный язык
  return (textId as any)[lang] || (textId as any).RU || '';
};
